syntax on
set background=dark

let g:jellybeans_overrides = {
\    'background': { 'ctermbg': 'none', '256ctermbg': 'none' },
\}
colo jellybeans

set tabstop=2
set softtabstop=2
set shiftwidth=2
set backspace=indent,eol,start
set expandtab
set autoindent
set mouse=a

inoremap ii <ESC>

filetype indent on

set number
set lazyredraw
set timeoutlen=150 ttimeoutlen=0
set clipboard=unnamed

" Change cursor shape between insert and normal mode in iTerm2.app
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
        let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
        endif

" VS Code terminal compatibility
if $TERM_PROGRAM == "vscode"
    set t_ut=
    set termguicolors
endif
