export DISABLE_UPDATE_PROMPT=true
export DISABLE_AUTO_UPDATE=true
export ZSH_DISABLE_COMPFIX=true

export PATH="/opt/homebrew/bin:/usr/bin:$PATH"

autoload -Uz compinit && compinit

source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
antidote load

alias vim='nvim'

export EDITOR=nvim
export VISUAL="$EDITOR"

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/jerry/.docker/completions $fpath)
# End of Docker CLI completions

eval "$(direnv hook zsh)"
eval "$(zoxide init --cmd cd zsh)"

source <(fzf --zsh)

alias ls="eza --icons --group-directories-first"
alias ll="eza -l --icons --group-directories-first"
alias la="eza -la --icons --group-directories-first"
alias tree="eza --tree --icons"

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#666666"
