export PATH="/usr/bin:$PATH"

autoload -Uz compinit && compinit

source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
antidote load

alias vim='nvim'

export EDITOR=nvim
export VISUAL="$EDITOR"

eval "$(direnv hook zsh)"

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/jerry/.docker/completions $fpath)
# End of Docker CLI completions

